spring:
  application:
    name: mybatis-plugin-pagination
  profiles:
    active: local
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  # mapper映射文件位置 === 必选属性,上述为可选属性,生产环境下关闭LOG输出
  mapper-locations: classpath:mapper/*.xml
  tenant-plugin:
    field-name: a.tenantId
#    ignore-table-names: test